runtime: custom
env: flex

runtime_config:
  document_root: public
  front_controller_file: index.php

env_variables:
    APP_ENV: "prod"
    DB_DATABASE: cloudtest
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_SOCKET: "/cloudsql/cloudpruebasql"
