monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested_stackdriver
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested_stackdriver:
            type: service
            id: monolog_psr_batch_logger
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

services:
    monolog_psr_batch_logger:
        class: Monolog\Handler\PsrHandler
        arguments: ['@google_cloud_stackdriver_psr_batch_logger']

    # PsrBatchLogger
    google_cloud_stackdriver_psr_batch_logger:
        class: Google\Cloud\Logging\PsrLogger
        factory: ['Google\Cloud\Logging\LoggingClient', 'psrBatchLogger']
        arguments: ['app']